version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: webapp-frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: webapp-backend
    environment:
      - PORT=4242
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=db
      - PGPORT=5432
    ports:
      - 4242:4242
    restart: on-failure
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    mem_reservation: 100m
    mem_limit: 200m
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
