version: '2'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: webapp-frontend
    ports:
      - 5173:5173

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: webapp-backend
    environment:
      - PORT=4242
    ports:
      - 4242:4242
